services:
  mongo:
    image: mongo:latest
    container_name: mongo-ticketmaster
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bpo
      MONGO_INITDB_ROOT_PASSWORD: labs.123
      MONGO_INITDB_DATABASE: db_ticketmaster
    volumes:
      - mongo_data:/data/db
    networks:
      - ticketing-network

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    container_name: event-service
    ports:
      - "5051:5050"
    depends_on:
      - mongo
    networks:
      - ticketing-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5059:5050"
    depends_on:
      - mongo
    networks:
      - ticketing-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "5056:5050"
    depends_on:
      - mongo
    networks:
      - ticketing-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "5057:5050"
    depends_on:
      - mongo
    networks:
      - ticketing-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "5055:5050"
    depends_on:
      - mongo
    networks:
      - ticketing-network

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "5054:5050"
    depends_on:
      - mongo
    networks:
      - ticketing-network

  nginx-gateway:
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "5050:80"
    depends_on:
      - event-service
      - user-service
      - order-service
      - inventory-service
      - payment-service
      - notification-service
    networks:
      - ticketing-network

volumes:
  mongo_data:

networks:
  ticketing-network:
    driver: bridge
    name: ticketing-network